#!/usr/bin/env ruby

if ENV['FP_ENV'] == 'test'
  require 'simplecov'
  require 'coveralls'
  SimpleCov.command_name "Unit Tests"
  Coveralls.wear_merged!
end

require_relative 'bootstrap_ar'
database = ENV['FP_ENV'] || 'development'
connect_to database

command = ARGV.shift # ARGV[0]
flags = {}
project_name = nil
ARGV.each do |argument|
  if argument.start_with? "--"
    flags[ argument.gsub("--","").to_sym ] = true
  else
    project_name = argument
  end
end

FuturePerfect.route(command, project_name, flags)
