#!/usr/bin/env ruby

require_relative 'bootstrap_ar'
database = ENV['FP_ENV'] || 'development'
connect_to database

# ARGV = [add, foo]
command = ARGV[0]
project_name = ARGV[1] # can be nil

params = { command: command, project: { name: project_name } }
controller = FuturePerfectController.new(params)

# This is a router:
if command == "add"
  controller.create
elsif command == "list"
  controller.index
elsif command == "remove"
  controller.destroy
elsif command == "start"
  controller.work
end
