#!/usr/bin/env ruby

if ENV['FP_ENV'] == 'test'
  require 'simplecov'
  require 'coveralls'
  SimpleCov.command_name "Unit Tests"
  Coveralls.wear!
end

require_relative 'bootstrap_ar'
database = ENV['FP_ENV'] || 'development'
connect_to database

command = ARGV[0]
project_name = ARGV[1] # can be nil

FuturePerfect.route(command, project_name)
